apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: quickstart
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_DATABASE: ""
  MYSQL_USER: "appuser"
  MYSQL_PASSWORD: ""

