apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-busybox
  name: pod-busybox
spec:
  containers:
  - image: busybox
    name: pod-busybox
    resources: {}
    command: ["/bin/sh"]
    args: ["-c", "touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600"] 
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
