apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-redis
  name: pod-redis
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: Exists
  containers:
  - image: redis
    name: pod-redis
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
