apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    env: demo
spec:
  selector:
    matchLabels:
      env: demo
  replicas: 1
  template:
    metadata:
      labels:
        env: demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.4-alpine
        ports:
        - containerPort: 80   
