apiVersion: batch/v1
kind: CronJob
metadata:
  name: 40daysofkubernetes
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command:
            - /bin/sh
            - -c
            - echo "40daysofkubernetes"
          restartPolicy: OnFailure       
