apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myds
  labels:
    env: demo
spec:
  selector:
    matchLabels:
      env: demo
  template:
    metadata:
      labels:
        env: demo
    spec:
      containers:
      - name: my-container
        image: nginx
        ports:
        - containerPort: 80
        
